#!/usr/bin/env bash
# Regenerate the pedagogy site images (gpt-image-2 via kie.ai). Run from this img/ folder.
cd "$(dirname "$0")"
G="node ../../gen-image.mjs"
$G "Empty hackathon room the morning of the event, long tables with closed and open laptops, sticky notes clustered on a glass wall, whiteboard with abstract diagram shapes (no letters), tangle of chargers, coffee cups, natural window light, olive-green accents on chairs, photorealistic, wide 24mm lens, calm documentary look, fine grain, no people, no faces, no text, no letters, no logos" hackathon.png 3:2 2K > hackathon.log 2>&1 &
$G "Youth research lab desk in a school: a stereo microscope beside a laptop showing only soft abstract green light on its screen, a small environmental sensor board wired to a breadboard, a glass jar with a green leaf branch, an open lab notebook with pencil graphs and sketches, wooden desk, warm afternoon light from the right, 50mm lens, photorealistic, muted palette with olive accent, no people, no hands, no text, no letters, no logos" gefen.png 3:2 2K > gefen.log 2>&1 &
$G "Overhead top-down photograph of a shared workshop table with four laptops arranged around it, each screen showing the same soft abstract olive-green node-and-line diagram glow (no letters), scattered sticky notes, pencils, a small robot chassis in the center, off-white table, even soft light, photorealistic, no people, no hands, no text, no letters, no logos" collab.png 16:9 2K > collab.log 2>&1 &
$G "Macro photograph of an electronics workbench: a green printed circuit board with through-hole components, a soldering iron resting on its stand with a wisp of smoke, resistors and capacitors sorted in a small tray, tweezers, a multimeter probe, dark cutting mat, side window light, 100mm macro lens, photorealistic, fine grain, no people, no hands, no text, no letters, no logos" hardware.png 3:2 2K > hardware.log 2>&1 &
$G "Tabletop smart-city model on a plywood board: small white foam-board buildings, miniature streets, tiny traffic lights and street lamps wired with thin wires to a microcontroller and breadboard at the edge of the board, a laptop beside it showing only an abstract glowing map of dots (no letters), overhead soft studio light, photorealistic macro, olive-green LED accents, no people, no hands, no text, no letters, no logos" smartcity.png 3:2 2K > smartcity.log 2>&1 &
wait
echo ALLDONE
