G="node ../../gen-image.mjs"
$G "Interior of a small owner-run neighborhood cafe-bakery in Israel at early morning before opening: wooden counter with a tablet stand and a phone resting on it, glass display of pastries, espresso machine, chairs still up on tables, warm low sunlight through the front window, calm, photoreal, editorial photography, shallow depth of field, no people, no text, no letters, no logos, no signage" hero.png 16:9 2K > hero.log 2>&1 &
$G "Top-down photo of a business process map being drawn on a large sheet of kraft paper on a wooden table: blank rectangular sticky notes in two colors connected by hand-drawn pencil arrows forming a flow, a pencil and a mug at the edge, soft daylight, photoreal, no people, no text, no letters, no logos, no writing on the notes" spec.png 3:2 2K > spec.log 2>&1 &
$G "Small shop back office at night: a laptop closed on a tidy desk, a smartphone face-up with its screen dimly glowing blank, a neat stack of paper invoices with a binder clip, a desk lamp casting warm light, keys and a coffee cup, everything handled and quiet, photoreal, no people, no text, no letters, no logos, no readable screen content" agents.png 3:2 2K > agents.log 2>&1 &
$G "Clean desk of a small business owner: an open laptop showing a blank soft grey screen, a smartphone beside it, and a paper notebook with pencil-sketched empty wireframe boxes and arrows for a mobile app layout, a ruler, natural window light, photoreal, no people, no text, no letters, no logos, no readable content on screens" apps.png 3:2 2K > apps.log 2>&1 &
$G "Compact product video setup in a small studio corner: a ceramic bowl on a white turntable inside a softbox light tent, mirrorless camera on a tripod pointed at it, a ring light and a small LED panel, cables neatly taped, dark backdrop, photoreal, cinematic light, no people, no text, no letters, no logos, no brand names on gear" video.png 3:2 2K > video.log 2>&1 &
$G "End of day at a small store counter: an old-fashioned receipt roll, a simple calculator, a paper ledger with a pen resting on it, a stack of coins, warm lamp light, wooden surface, closeup, photoreal, shallow depth of field, no people, no text, no letters, no numbers visible, no logos" bottomline.png 3:2 2K > bottomline.log 2>&1 &
wait
echo ALLDONE
